### ISSUE TITLE
Local Install

### ISSUE THREAD

**Issue by vsoch** [NERSC/shifter#192]
If I wanted to install this on my local machine (without needing / having a huge cluster) and just wanting a simple build --> run for a shifter container, is this an intended use case? Or is the idea to ship Docker images and run on a shared resource (and so local testing would coincide with using Docker). Thanks!

**Comment by scanon** [comment]
Take a look at this and see if it meets your needs...

https://github.com/NERSC/Shifter-Tutorial/tree/master/examples/shifter-in-a-box

**Comment by vsoch** [comment]
It's shifter in a box!! :D 

Yes I'll give it a try and report back, thank you!

**Comment by vsoch** [comment]
okay I have a question. When you bind the volume `shifter` in [this line](https://github.com/NERSC/Shifter-Tutorial/tree/master/examples/shifter-in-a-box#usage) is the shifter volume referring to the entire [installation repository[(https://github.com/NERSC/shifter) or the [shifter folder](https://github.com/NERSC/Shifter-Tutorial/tree/master/examples/shifter) in the same examples folder?

**Comment by scanon** [comment]
It is just a name attached to a docker volume. The volume mount is so the state gets retained if you stop and restart the container. It is not strictly required but helpful. You could use a different label other than shifter.

**Comment by vsoch** [comment]
Tiny progress! How should I debug this?

```
[root@b26f117c8a79 /]# /src/start.sh
Starting services
about to fork child process, waiting until server is ready for connections.
forked process: 24
1+0 records in
1+0 records out
512 bytes (512 B) copied, 0.000123936 s, 4.1 MB/s
Starting Shifter Services
[root@b26f117c8a79 /]# munged: Notice: Running on "b26f117c8a79" (172.17.0.7)
munged: Info: PRNG seeded with 1024 bytes from "/dev/urandom"
munged: Info: Updating supplementary group mapping every 3600 seconds
munged: Info: Enabled supplementary group mtime check of "/etc/group"
munged: Notice: Starting munge-0.5.11 daemon (pid 34)
munged: Info: Created 2 work threads
munged: Info: Found 0 users with supplementary groups in 0.001 seconds
child process started successfully, parent exiting

[root@b26f117c8a79 /]# su - auser
[auser@b26f117c8a79 ~]$ shifterimg pull vanessa/snakemake.scif
ERROR: failed to contact the image gateway.
[auser@b26f117c8a79 ~]$ shifterimg pull busybox               
ERROR: failed to contact the image gateway.
[auser@b26f117c8a79 ~]$ /src/test.sh 
Testing munge
Test pull
ERROR: failed to contact the image gateway.
[auser@b26f117c8a79 ~]$ 
```

**Comment by scanon** [comment]
@vsoch I've sent you a Slack invite.  But I would suggest looking at /var/log/shifter_imagegw/error.log since it sounds like the image gateway didn't come up.  You can look at the /src/start.sh to see what things are being launched.

**Comment by vsoch** [comment]
ah ok, so this is an issue with connecting to MongoDB at port 27017:
```
ConnectionFailure: could not connect to localhost:27017: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/usr/lib64/python2.7/site-packages/shifter_imagegw/api.py", line 70, in <module>
    mgr = ImageMngr(config, logname=logname)
  File "/usr/lib64/python2.7/site-packages/shifter_imagegw/imagemngr.py", line 115, in __init__
    self.mongo_init()
  File "/usr/lib64/python2.7/site-packages/shifter_imagegw/imagemngr.py", line 121, in mongo_init
    client = MongoClient(self.config['MongoDBURI'])
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 337, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: could not connect to localhost:27017: [Errno 111] Connection refused
2018-02-22 07:54:44 [42] [INFO] Worker exiting (pid: 42)
2018-02-22 07:54:44 [33] [INFO] Shutting down: Master
2018-02-22 07:54:44 [33] [INFO] Reason: Worker failed to boot.
```
First I can confirm it's not some difference between the user and being root:

```
# Here I'm the user
[root@b26f117c8a79 /]# su - auser
Last login: Thu Feb 22 16:48:05 UTC 2018 on pts/0
[auser@b26f117c8a79 ~]$ exit
logout

# Now I'm root
[root@b26f117c8a79 /]# shifterimg pull busybox
ERROR: failed to contact the image gateway.
```
We can see from the Dockerfile that the contents of config in the repo are copied to /src at the container base, oh wait we already know we want to look at start.sh, let's do that.

```
grep -c squash /proc/filesystems 
1
# squash fs module is loaded

[auser@b26f117c8a79 ~]$ ls /data/db/
_tmp  journal  local.0  local.ns  mongod.lock
# database exists

[auser@b26f117c8a79 ~]$ ls /data/images/cache/
# cache exists

# Here is the bug...
[auser@b26f117c8a79 ~]$ mongod --smallfiles --fork --logpath=/var/log/mongodb/mongo.log --pidfilepath /mongo.pid   
about to fork child process, waiting until server is ready for connections.
forked process: 164
ERROR: child process failed, exited with error number 1
```
Let's investigate mongo log file...

```
cat /var/log/mongodb/mongo.log 
2018-02-22T07:54:42.143+0000 [initandlisten] MongoDB starting : pid=24 port=27017 dbpath=/data/db 64-bit host=b26f117c8a79
2018-02-22T07:54:42.143+0000 [initandlisten] db version v2.6.12
2018-02-22T07:54:42.143+0000 [initandlisten] git version: nogitversion
2018-02-22T07:54:42.143+0000 [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2018-02-22T07:54:42.143+0000 [initandlisten] build info: Linux buildvm-16.phx2.fedoraproject.org 4.8.12-300.fc25.x86_64 #1 SMP Fri Dec 2 17:52:11 UTC 2016 x86_64 BOOST_LIB_VERSION=1_53
2018-02-22T07:54:42.143+0000 [initandlisten] allocator: tcmalloc
2018-02-22T07:54:42.143+0000 [initandlisten] options: { processManagement: { fork: true, pidFilePath: "/mongo.pid" }, storage: { smallFiles: true }, systemLog: { destination: "file", path: "/var/log/mongodb/mongo.log" } }
2018-02-22T07:54:42.156+0000 [initandlisten] journal dir=/data/db/journal
2018-02-22T07:54:42.156+0000 [initandlisten] recover : no journal files present, no recovery needed
2018-02-22T07:54:42.699+0000 [initandlisten] preallocateIsFaster=true 4.22
2018-02-22T07:54:43.248+0000 [initandlisten] preallocateIsFaster=true 4.28
2018-02-22T07:54:44.785+0000 [initandlisten] preallocateIsFaster=true 4.24
2018-02-22T07:54:44.785+0000 [initandlisten] preallocating a journal file /data/db/journal/prealloc.0
2018-02-22T07:54:45.112+0000 [initandlisten] preallocating a journal file /data/db/journal/prealloc.1
2018-02-22T07:54:45.432+0000 [initandlisten] preallocating a journal file /data/db/journal/prealloc.2
2018-02-22T07:54:45.733+0000 [initandlisten] allocating new ns file /data/db/local.ns, filling with zeroes...
2018-02-22T07:54:45.794+0000 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
2018-02-22T07:54:45.794+0000 [FileAllocator] creating directory /data/db/_tmp
2018-02-22T07:54:45.810+0000 [FileAllocator] done allocating datafile /data/db/local.0, size: 16MB,  took 0.006 secs
2018-02-22T07:54:45.810+0000 [initandlisten] build index on: local.startup_log properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "local.startup_log" }
2018-02-22T07:54:45.811+0000 [initandlisten] 	 added index to empty collection
2018-02-22T07:54:45.811+0000 [initandlisten] waiting for connections on port 27017
2018-02-22T07:55:45.735+0000 [clientcursormon] mem (MB) res:36 virt:302
2018-02-22T07:55:45.735+0000 [clientcursormon]  mapped (incl journal view):64
2018-02-22T07:55:45.735+0000 [clientcursormon]  connections:0
...
```

then that last line goes forever! So I think it's just the port? Let's exit and try again.

```
docker run -it --rm --expose 27017 --privileged -v shifter:/data scanon/shifterbox
[root@1f76aae5b5bc /]# /src/start.sh
Starting services
about to fork child process, waiting until server is ready for connections.
forked process: 19
child process started successfully, parent exiting
1+0 records in
1+0 records out
512 bytes (512 B) copied, 0.000234286 s, 2.2 MB/s
Starting Shifter Services
[root@1f76aae5b5bc /]# munged: Notice: Running on "1f76aae5b5bc" (172.17.0.2)
munged: Info: PRNG seeded with 1024 bytes from "/dev/urandom"
munged: Info: Updating supplementary group mapping every 3600 seconds
munged: Info: Enabled supplementary group mtime check of "/etc/group"
munged: Notice: Starting munge-0.5.11 daemon (pid 36)
munged: Info: Created 2 work threads
munged: Info: Found 0 users with supplementary groups in 0.000 seconds

[root@1f76aae5b5bc /]# 
```
Now the user...
```
su - auser
[auser@1f76aae5b5bc ~]$ shifterimg pull busybox
2018-02-22T17:03:03 Pulling Image: docker:busybox, status: READY
````

Woohoo success! How did you get it running without exposing the port?

**Comment by vsoch** [comment]
See https://github.com/NERSC/Shifter-Tutorial/pull/2/files to add the note to the README, for future dinosaurs gone astray.

**Comment by vsoch** [comment]
Thanks again for the help with this!

**Comment by sat0635** [comment]
> See https://github.com/NERSC/Shifter-Tutorial/pull/2/files to add the note to the README, for future dinosaurs gone astray.

thank you!!

**Comment by vsoch** [comment]
You're welcome! :)
