### ISSUE TITLE
provide imagegw interface for importing a cpio or tar file and converting to shifter image

### ISSUE THREAD

**Issue by dmjacobsen** [NERSC/shifter#54]
some users, especially those on alternate architectures may not be able to easily bootstrap on docker yet.  suggest adding a new bit to imagegw api and image manager to allow users to import a tar/cpio file already on the platform in question

perhaps something like a POST to
/api/push/&lt;platform&gt;/file/&lt;label:tag&gt;

(so potentially using the existing "push" infrastructure with a "file" type)
with a POST data
path=/path/to/the/file
config=&lt;json-encoded open container formatted spec&gt;

the worker would then attempt to read the file, determine the type, extract it and perform the conversion/transfer per usual.

The opencontainer manifest spec is here: https://github.com/opencontainers/image-spec/tree/master/schema

The client interface would collect the necessary information.  For the time being we can probably just focus on getting architecture and environment details.

We had discussed some methods for creating ids for these types so they can sit in the same namespace as the docker images -- something like generating a manifest for it and using a checksum on the manifest which would contain a checksum (of some sort) of the input file, thereby allowing data to change and metadata to remain static, or allow data to remain static and metadata to change.

**Comment by chrissamuel** [comment]
Leveraging this to push in a private docker container for testing without pushing to a docker registry would be handy as well.

**Comment by lijiang2014** [comment]
Hi  @chrissamuel , could you tell me how to config shifter with a local docker registry ?  I always got errors ...

**Comment by dmjacobsen** [comment]
@lijiang2014 take a look at the test.json.example as a possible reference for how to add different locations to the imagemanager:

https://github.com/NERSC/shifter/blob/master/imagegw/test.json.example

Just change the `url:` field to match yours (based on issue #134, I think this will only work if the registry is listening on port 443 right now).

-Doug

**Comment by lijiang2014** [comment]
Hi @dmjacobsen .
Thx for your advice , I follow the issue #134  change : 

`if protocol == 'http':
        conn = httplib.HTTPConnection(server)`
into : 
`if protocol == 'http':
        conn = httplib.HTTPConnection(server , 'port')`

It seems build the connection and works , but the pull also failed ,and i don't know what's wrong, the log is here : 

`[2016-09-23 10:34:33,461: WARNING/Worker-31] pulling image tensorflow:th2.1
[2016-09-23 10:34:33,497: ERROR/Worker-31] ls stderr: ls: cannot access /WORK/app/images/001164cb10b52edcf7974fe470d70bf9c336a8cfd260ec4c2e7f0fb3bc47cbbb.meta: No such file or directory
[2016-09-23 10:34:33,502: ERROR/Worker-31] ls stderr: ls: cannot access /WORK/app/images/001164cb10b52edcf7974fe470d70bf9c336a8cfd260ec4c2e7f0fb3bc47cbbb.squashfs: No such file or directory
[2016-09-23 10:35:53,280: WARNING/Worker-31] 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)
[2016-09-23 10:35:53,281: ERROR/Worker-31] ERROR: dopull failed system=mycluster tag=tensorflow:th2.1
[2016-09-23 10:35:53,281: WARNING/Worker-31] 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)
[2016-09-23 10:35:53,445: ERROR/MainProcess] Task shifter_imagegw.imageworker.dopull[1075917e-e668-4e8f-84cf-f21a05382feb] raised unexpected: UnicodeDecodeError('ascii', '/etc/ssl/certs/Certinomis_-_Autorit\xc3\xa9_Racine.pem', 35, 36, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/shifter_imagegw/imageworker.py", line 346, in dopull
    if not pull_image(request,updater=us):
  File "/usr/lib64/python2.7/site-packages/shifter_imagegw/imageworker.py", line 171, in pull_image
    dh.extractDockerLayers(expandedpath, dh.get_eldest(), cachedir=cdir)
  File "/usr/lib64/python2.7/site-packages/shifter_imagegw/dockerv2.py", line 544, in extractDockerLayers
    tfp.extractall(path=basePath,members=members)
  File "/usr/lib64/python2.7/tarfile.py", line 2047, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib64/python2.7/tarfile.py", line 2084, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib64/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)
(END)`

>  tensorflow:th2.1 is a local docker registry image i got from a tar file , i could use  ` docker pull 10.127.48.6:5000/tensorflow:th2.1 `  to pull this image . I want to use shifter to run this image , but also got problems ...

**Comment by scanon** [comment]
This functionality exist with the import that was added.  Closing.
